### ISSUE TITLE
[FEATURE REQUEST] Github action to release openebs components

### ISSUE THREAD

**Issue by akhilerm** [kmova/release-helper#2]
Currently Openebs relies on shell scripts which uses travis specific envirnoment variables to perform downstream release tagging. As we are moving away from travis to github actions, a `release-helper` action could be useful to perform openebs releases.

Instead of using travis scripts , an action could be used as follows
```yaml
downstream-release:
  runs-on: ubuntu-latest
  needs: ['componentA', 'componentB', 'componentC']
  steps:
    - name: Release
      uses: kmova/release-helper@master
      with:
        tag: v2.6.0
        repos: |
          openebs/maya
          openebs/jiva
          openebs/local-pv
```
